#!/bin/expect
set timeout 10

set password [lindex $argv 0]
set port [lindex $argv 1]
set dest_ip [lindex $argv 2]
set command [lindex $argv 3]

spawn ssh -p $port $dest_ip $command
    expect {
        "(yes/no)?"
        {
            send "yes\n"
            expect "*assword:" { send "$password\n"}
        }
        "*assword:"
        {
            send "$password\n"
        }
    }
expect eof

