#!/usr/bin/expect
set timeout 10

set password [lindex $argv 0]
set port [lindex $argv 1]
set src_file [lindex $argv 2]
set dest_file [lindex $argv 3]
spawn scp -P $port $src_file $dest_file
    expect {
        "(yes/no)?"
        {
            send "yes\n"
            expect "*assword:" { send "$password\n"}
        }
        "*assword:"
        {
            send "$password\n"
        }
    }
expect "100%"
expect eof

