- name: 部署kube-proxy
  template: src={{ item }} dest=/etc/kubernetes/CoreAddons/{{ item.split('.')[:-1]|join('.') }}
  with_items:
    - kube-proxy.yml.j2
  when: not kube_proxy_bin
  tags:
    - kube-proxy
    - core

- command: kubectl apply -f /etc/kubernetes/CoreAddons/kube-proxy.yml
  when: not kube_proxy_bin
  tags:
    - kube-proxy
    - core


- name: 渲染kube-flannel.yml文件模板
  template: src={{ item }} dest=/etc/kubernetes/CoreAddons/{{ item.split('.')[:-1]|join('.') }}
  with_items:
    - 'kube-flannel.yml.conf.j2'
  when: Net_Choose is defined and Net_Choose == 'flannel'

- name: 部署flannel
  command: kubectl apply -f /etc/kubernetes/CoreAddons/kube-flannel.yml


- name: 渲染coredns,metrics-server文件模板
  template: src={{ item }} dest=/etc/kubernetes/CoreAddons/{{ item.split('.')[:-1]|join('.') }}
  with_items:
    - 'coredns.yml.j2'
    - 'metrics-server.yml.j2'
  tags:
    - core

- name: 部署coredns
  command: kubectl apply -f /etc/kubernetes/CoreAddons/coredns.yml
  tags:
    - core

- name: 部署metrics
  command: kubectl apply -f /etc/kubernetes/CoreAddons/metrics-server.yml
  tags:
    - core

#- file:
#    path: "{{ kubernetes_path }}/CoreAddons/calico"
#    state: directory
#  when: Net_Choose is defined and Net_Choose != 'flannel'
#- name: 渲染calico文件模板
#  template:
#    src: "{{ item }}"
#    dest: "{{ kubernetes_path }}/CoreAddons/calico/{{ item.split('/')[-1].split('.')[:-1]|join('.') }}"
#  with_fileglob:
#    - templates/calico/*
#  when: Net_Choose is defined and Net_Choose != 'flannel'


#- name: 建立Kube-proxy  CoreDNS (calico or flannel)
#  shell: |
#    :;{{ kubectl_path }}/kubectl apply -f CoreAddons/kube-proxy.yml.conf;sleep 6;
#    {{ kubectl_path }}/kubectl apply -f CoreAddons/coredns.yml.conf;
#    {{ kubectl_path }}/kubectl apply -f CoreAddons/{% if Net_Choose == 'flannel' %}kube-flannel.yml.conf{% else %}calico{% endif %};sleep 6;
#    {{ kubectl_path }}/kubectl apply -f CoreAddons/metrics-server.yml.conf;sleep 1;
#  args:
#    chdir: "{{ kubernetes_path }}"

